
steps:
  - name: python:3.7
    entrypoint: make
    args: ["setup"]
  
  - name: python:3.7
    entrypoint: make
    args: ["source"]

  - name: python:3.7
    entrypoint: make
    args: ["install"]
  
  - name: python:3.7
    entrypoint: make
    args: ["lint-check"]
  
  - name: python:3.7
    entrypoint: make
    args: ["test"]

