
# Each step runs in a separate container, so you should do it all in one step

steps:
  - name: python:3.7
    id: Test
    entrypoint: /bin/sh
    args:
    - -c
    - |
      make setup
      make source
      make install
      make lint-check
      make test
